### ISSUE TITLE
Create seed exchange list for TUR botanic garden

### ISSUE THREAD

**Issue by AnniinaK** [luomus/kotka-v3#14]
Luomus botanic garden has this list page: https://kotka.luomus.fi/seed/list

Create a similar page, URL can be something like https://kotka.luomus.fi/seed/list-tur or whatever similar

Use tag/dataset GX.18775 and branch location/collection HR.6198

After this, we can see how the list looks like with Turku data but with Luomus formatting, and estimate how much changes are needed.

**Comment by MLumme** [comment]
No, that should be enough to put it together.

**Comment by MLumme** [comment]
@AnniinaK actually, could we make the list for turku accessible with url /seed/list/tur instead of /seed/list-tur, it results in bit neater code?

**Comment by AnniinaK** [comment]
I sent this for Merja in the Turku botanic garden for review
