### ISSUE TITLE
Fix mapping for fields and add a new field on Label designer

### ISSUE THREAD

**Issue by AnniinaK** [luomus/kotka-v3#3]
Hi,
Taxon consept (sec) field doesn't show up on the labels even if it has been added to the label design.

Eli Taxon consept (sec) -kentän sisältö ei tule etiketteihin näkyviin vaikka kyseinen kenttä on valittavissa etikettipohjaan. Eli edelleen tämän tiedon joutuu ensin kopioimaan excelissä johonkin näkyviin tulevaan kenttään, jotta etiketit saa tehtyä ja sitten poistamaan tuplatiedon excelistä.

- [x] Add ObservationID available on Label designer
- [x] Add mapping for fields bold, transcriberNotes, sec and higherGeography
- [x] Add mapping for ObjectID

**Comment by aorin** [comment]
@AnniinaK  Can be tested at https://kotkatest.luomus.fi. I added a field mapping for 4 fields that were missing it (`bold`, `transcriberNotes`, `sec` and `higherGeography`). There were still two label designer fields, `objectID` and `samplePreparationID`, that didn't seem to be mapped to any `MY.document` fields. Should we do something to them?

**Comment by AnniinaK** [comment]
@aorin Thanks! Yes I think those two need to be mapped too. If possible?

**Comment by aorin** [comment]
@AnniinaK  so is the `samplePreparationID` the id of the `MF.sample`? How it differs from the label designer `ID` field? And what about `objectID`, I can't see anything like that in the schema

**Comment by AnniinaK** [comment]
@aorin Yes, samplePreparationID is the if for MF.sample, it is automatically generated on Kotka, as a derivative from the document ID. Example here: https://kotka.luomus.fi/view?uri=http://id.luomus.fi/LH.1, it has two samples, and they have identifiers http://id.luomus.fi/LH.1#P1 and http://id.luomus.fi/LH.1#P2. 

Label designer other ID fields:

- URI full URI identifier http://id.luomus.fi/LH.1
- ID qname part of the identifier, so e.g. LH.1
- ObjectID only the part after the last dot so "1" in that example case.

ObjectID is called MYObjectID on Kotka specimen entry form (https://kotka.luomus.fi/botany/specimens/add, fifth row) and Kotka excel template. 

Sorry I don't know how these are technically handled and why they are not on schema :/

**Comment by aorin** [comment]
Ok, so if we take the http://id.luomus.fi/LH.1 as an example, if you print labels through "Search specimens", you get one label with

- URI http://id.luomus.fi/LH.1
- ID LH.1

If you print the labels through "Search preparations/samples", you get two labels and the first one has

- URI http://id.luomus.fi/LH.1#P1
- ID LH.1#P1

It looks to me that the `samplePreparationID` field is unnecessary as it's the same as the ID field (if you print a sample label). And looking at the current logic, it's not clear if the `objectID`  is `1` or `1#P1`

**Comment by AnniinaK** [comment]
@aorin very good point! I had completely forgotten you can access Label designer also from "Search preparations/samples". So yes, samplePreparationID is unnecessary. 

I would say 1#P1 would be the objectID, thinking it is just everything that comes after the dot after the namespace. But not sure though

**Comment by aorin** [comment]
@AnniinaK can be tested at https://kotkatest.luomus.fi. The objectID format can be changed later if needed but at least it's not empty now

**Comment by AnniinaK** [comment]
@aorin Tested all the fields (with preview, not actual PDF) and all good :)
